 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: training-project
 spec:
   replicas: 1
   template:
     metadata:
       name: training-project
       labels:
         run: training-project
     spec:
       containers:
         - name: training-project
           image: anhegde2/training-project:v1
           imagePullPolicy: Always
           ports:
           - containerPort: 7000
           envFrom:
             - configMapRef:
                 name: training-project
             - secretRef:
                 name: training-project-secret
                 
