apiVersion: v1
kind: Service
metadata:
  name: training-project
  labels:
    run: training-project
spec:
  type: NodePort
  selector:
    run: training-project
  ports:
    - name: training-project
      protocol: TCP
      port: 7000
      targetPort: http
      nodePort: 31889
